version: '3.8'

services:
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - '9092:9092'
      - '9093:9093'
    volumes:
      - 'kafka_data:/bitnami/kafka'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 15s  # Increased interval for longer Kafka startup time
      retries: 12  # Increased retries to give Kafka more time to start

  kafka-connect:
    image: 'confluentinc/cp-kafka-connect:latest'
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=kafka:9092
      - CONNECT_REST_ADVERTISED_HOST_NAME=kafka-connect
      - CONNECT_GROUP_ID=kafka-connect-group
      - CONNECT_CONFIG_STORAGE_TOPIC=connect-configs
      - CONNECT_OFFSET_STORAGE_TOPIC=connect-offsets
      - CONNECT_STATUS_STORAGE_TOPIC=connect-statuses
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.storage.StringConverter
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
    ports:
      - '8083:8083'
    depends_on:
      kafka:
        condition: service_healthy  # Ensure Kafka is fully started before Kafka Connect starts

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    container_name: kafka-ui
    ports:
      - '8090:8090'  # Use the default port 8090 for Kafka UI
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    volumes:
      - './kafka-ui-config.yml:/etc/kafkaui/dynamic_config.yaml'

  spark:
    image: 'bitnami/spark:latest'
    container_name: spark-master
    environment:
      - SPARK_UI_PORT=4040
    ports:
      - '4040:4040'
    volumes:
      - 'spark_data:/bitnami/spark'

volumes:
  kafka_data:
    driver: local
  spark_data:
    driver: local
